import type { FlowSkill, FlowTool, FlowSkill as FlowSkillType, SkillStep } from "../types";

const steps: SkillStep[] = [
  { type: "skill", id: "summarize_file", label: "Summarize source file" },
  { type: "tool", id: "current_time", label: "Timestamp report" },
];

export const createReportSkill: FlowSkill = {
  id: "create_report",
  name: "Create Report",
  description: "Generate a structured report by summarizing a file and adding metadata",
  icon: "file-chart",
  steps,
  async execute(input, toolRegistry, skillRegistry): Promise<string> {
    const summFileSkill = skillRegistry.get("summarize_file");
    const timeTool = toolRegistry.get("current_time");

    if (!summFileSkill) {
      return "Required skill not available: summarize_file";
    }

    const summary = await summFileSkill.execute(input, toolRegistry, skillRegistry);
    const timeResult = timeTool
      ? await timeTool.handler({ timezone: "UTC", format: "short" })
      : { success: true, result: new Date().toISOString() };

    return [
      `# Report`,
      `**Generated:** ${timeResult.result}`,
      "",
      "## Summary",
      summary,
      "",
      "---",
      "*Report generated by Ave AI*",
    ].join("\n");
  },
};
